### ISSUE TITLE
'TypeError: seasonal_decompose() got an unexpected keyword argument 'freq''

### ISSUE THREAD

**Issue by jcm36** [mullenkamp/detidelevel#1]
Hi There,

DeTideLevel does not appear to work any longer as the 'freq' argument in seasonal_decompose() has been replaced with a 'period' argument.  

Would this be easy to correct?

Thanks,

**Comment by mullenkamp** [comment]
Hi,

Yeah, probably. I'm impressed someone else is using this ;)
I'll try to update it later this week/weekend.

**Comment by jcm36** [comment]
> Hi,
> 
> Yeah, probably. I'm impressed someone else is using this ;) I'll try to update it later this week/weekend.

Thank you, that would be amazing.

**Comment by mullenkamp** [comment]
I changed the parameter as you suggested. Let me know if it works...I didn't actually test it. If it still fails...then I might need to be a bit more thorough.

**Comment by jcm36** [comment]
> I changed the parameter as you suggested. Let me know if it works...I didn't actually test it. If it still fails...then I might need to be a bit more thorough.

Excellent, thank you! That has worked perfectly.
It was throwing an error if I didn't specify an Freq input, but once I specified that it has worked perfectly.  Thank you - this is a very useful function
